persistence:
  homarrDatabase:
    # -- Enable homarr-database persistent storage
    enabled: false
    # -- homarr-database persistent storage name
    name: "homarr-database"
    # -- homarr-database storage class name
    storageClassName: "local-path"
    # -- homarr-database access mode
    accessMode: "ReadWriteOnce"
    # -- homarr-database storage size
    size: "50Mi"
    # -- homarr-database mount path inside the pod
    mountPath: "/appdata/db"
    # -- homarr-database optional volumeClaimName to target specific PV
    volumeClaimName: ""
  homarrImages:
    # -- Enable homarr-images persistent storage
    enabled: false
    # -- homarr-images persistent storage name
    name: "homarr-images"
    # -- homarr-images storage class name
    storageClassName: "local-path"
    # -- homarr-images access mode
    accessMode: "ReadWriteOnce"
    # -- homarr-images storage size
    size: "50Mi"
    # -- homarr-images mount path inside the pod
    mountPath: "/images"
    # -- homarr-images optional volumeClaimName to target specific PV
    volumeClaimName: ""
